apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollamarun-labeler
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ollamarun-ns-labeler-{{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ollamarun-ns-labeler-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ollamarun-ns-labeler-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: ollamarun-labeler
    namespace: {{ .Release.Namespace }}
