apiVersion: v1
kind: Service
metadata:
  name: ollamarun-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: ollamarun
  ports:
    - protocol: TCP
      name: api
      port: 11434
      targetPort: 11434
