apiVersion: v1
kind: Service
metadata:
  name: openclaw-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: openclaw
  ports:
    - protocol: TCP
      name: gateway
      port: 18789
      targetPort: 18789
